name: CityBuild-System
author: ScienceCode
version: 1.0
main: de.sciencecode.cbsystem.main.Main
commands:
  rang:
  clearlag:
  warp:
  delwarp:
    aliases: [removewarp]
  setwarp:
    aliases: [createwarp]
  plot:
    aliases: [p]
  rand:
  ban:
  unban:
  mute:
  unmute:
  msg:
  togglemsg:
    aliases: [msgtoggle]
  dailyreward:
  spawndailyreward:
  spawnshop:
  gamemode:
    aliases: [gm]
  fly:
  giveall:
  chatclear:
    aliases: [cc]
  enderchest:
    aliases: [ec]
  tpa:
  tpahere:
  heal:
  list:
  home:
  sethome:
  delhome:
  vanish:
    aliases: [v]
  rename:
  head:
    aliases: [kopf]
  tp:
  tphere:
  spawn:
  setspawn:
  kurse:
  onlinetime:
    aliases: [ot]
  kick:
  bewerbung:
  nick: