package cloud.evaped.citybuild.utils.nick;

import cloud.evaped.citybuild.main.CityBuildCore;
import java.io.File;
import java.util.List;
import org.bukkit.configuration.file.FileConfiguration;

public class NickFile
{
  public NickFile() {}
  
  public static void updateNickNameFile()
  {
    File FILE = new File("plugins/CityBuild/Inventory/", "nicknames.yml");
    FileConfiguration file = org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(FILE);
    
    List<String> list = new java.util.ArrayList();
    list.add("SeaMonkey7");
    list.add("1000PercentCqt");
    list.add("Gollax");
    list.add("Duck_Lmao");
    list.add("Koolz");
    list.add("Rexisea");
    list.add("Spyrol1");
    list.add("DoomRiko");
    list.add("Evil_Commander");
    list.add("Danoah47");
    list.add("EzzKite");
    list.add("IBimsBlackOut");
    list.add("GloHD_YT");
    list.add("Ente_am_zocken");
    list.add("Einfach_Erik");
    list.add("AnErr");
    list.add("Chimalia");
    list.add("GodAylin");
    list.add("1JohannesSpielt");
    list.add("2SneakforU");
    list.add("AlexandroDiaz");
    list.add("KomischesHase");
    list.add("Freeze_LP05");
    list.add("EpicKid04");
    list.add("CatLove321");
    list.add("Blacky_san");
    list.add("XFinn845");
    list.add("SeaMonkey7");
    list.add("SunnyBeaziNoupi");
    list.add("_EyeofDoom_");
    list.add("riad2008");
    list.add("jonutdex");
    list.add("Jose_PVP");
    list.add("Nisloki");
    list.add("sophiegamer140");
    list.add("sanfen");
    list.add("lordlord98");
    list.add("Unreal_Death");
    list.add("medofox");
    list.add("IAVZ_14");
    list.add("Applonia");
    list.add("Emmyx2005");
    list.add("ArmyFoxxx");
    list.add("Kouii");
    list.add("MBr99");
    list.add("DevilDani");
    list.add("LikeAKitty");
    list.add("xpod12");
    list.add("Twerxer");
    list.add("vorsichtige_");
    list.add("Fekel2");
    list.add("EnergieReaktor");
    list.add("Pizzaschaf");
    list.add("PrideLife");
    list.add("Silv3rsur73r");
    list.add("Zsalter1");
    list.add("Tobi_AT");
    list.add("LostCoiikie");
    list.add("Luis1902");
    list.add("Nikita_Kyiv");
    list.add("Wolkenfarmer");
    list.add("loligus1");
    list.add("DrSepp");
    list.add("Bedeutungsloser");
    list.add("WodkaOrangensaft");
    list.add("Klxtzii");
    list.add("Noupak");
    list.add("Itz_Chaika");
    list.add("Flugwafel44");
    list.add("MrsFleur");
    list.add("Blackaar");
    list.add("GerLexHD");
    list.add("PrideLife");
    list.add("stylo19");
    list.add("MrPaddel");
    list.add("DerMainer");
    list.add("guteSarah");
    list.add("Carl1_1");
    list.add("Ilativ");
    list.add("Kopfnuss_Kalli");
    list.add("JansBurg");
    list.add("Dreemstaria");
    list.add("Die_CrackEnte");
    list.add("Mondherz");
    list.add("Kikachuuu");
    list.add("Halvehahn1");
    list.add("MrsMiaa");
    list.add("Jebedi");
    list.add("ImKyubii");
    list.add("Myeaa");
    list.add("Luigi726");
    list.add("LeiskornPaula");
    list.add("Xyrus");
    list.add("Strickt");
    list.add("MockzZ");
    list.add("Goberso");
    list.add("SilverNight13");
    list.add("CyberSec");
    list.add("xHigh420x");
    list.add("Steveo4");
    list.add("Th3Gam3r62");
    list.add("ericvoss");
    list.add("IamHotTrash");
    list.add("Dmanplaying");
    list.add("clarkeymine");
    list.add("Complex_Setup");
    list.add("ItsAlchimist");
    list.add("Shrumy");
    list.add("Sky_Lord_");
    list.add("Goky888");
    list.add("NJWB");
    list.add("_XenoVortex_");
    list.add("GhostLyd");
    list.add("_xX_FreshVibes_Xx_");
    list.add("blucu");
    list.add("Spyrol");
    list.add("Jennnaa");
    list.add("AnotherOne_");
    list.add("Vertraeumter");
    list.add("WayTex");
    list.add("ByRays");
    list.add("LilGuccii");
    list.add("Kronos_76");
    list.add("DreamSyndrom");
    list.add("WUDMerlin");
    list.add("nyexee");
    list.add("Philibuz");
    list.add("MusRaus");
    list.add("_whiteCube_");
    list.add("Muxil");
    list.add("ZwergPanda");
    list.add("Garfield09");
    list.add("Schluppi");
    list.add("Krawall");
    list.add("Sanice");
    list.add("SHP_ART");
    list.add("Lhyre");
    list.add("NexexGaming");
    list.add("SlyKing");
    list.add("VectrumYT");
    list.add("Pezi90");
    list.add("Recher_HD");
    list.add("Tobi_Mahoni");
    list.add("Frostimax");
    list.add("_Bosch_");
    list.add("Taduran");
    list.add("Xdfire");
    list.add("Xelario_X");
    list.add("lumann889");
    list.add("Schwarzerregen");
    list.add("Killi44");
    list.add("Tramix");
    list.add("FireCrack_");
    list.add("Eric_2002");
    list.add("Rheepy");
    list.add("SRVerbot");
    list.add("OmaYeezy");
    list.add("Rocketmulle");
    list.add("Wolfjoke");
    list.add("die_Entertaste");
    list.add("Bims17Zwerg");
    list.add("Burafer");
    list.add("Fela24");
    list.add("Suzusa");
    list.add("Bodt96");
    list.add("bilse1989");
    list.add("Nooovaa");
    list.add("gallierobelix");
    list.add("1Rafael");
    list.add("ImVentrix");
    list.add("Abation");
    list.add("Big_Bozz");
    list.add("Sanice");
    list.add("iLezug_");
    list.add("NeoDAce");
    list.add("LectonYT");
    list.add("SkeddiHD");
    list.add("iPlaxo");
    list.add("AndySMCR");
    list.add("melowow");
    list.add("Brocco_Lee");
    list.add("Knuddel_michXxmc_zockerxX");
    list.add("BySkylight");
    list.add("Vxtraeumter");
    list.add("Catiii");
    list.add("85silver");
    list.add("JaiJai");
    list.add("Stone__Cold");
    list.add("StroblTV");
    list.add("Alea1337");
    list.add("DerMattiZocker");
    list.add("Fordex");
    list.add("Tschlaubii");
    list.add("WelpieHD");
    list.add("zerstoererflo");
    list.add("xIamAngelPlayer");
    list.add("Woodny");
    list.add("HoppiMoppi");
    list.add("GamerX100");
    list.add("Zeroharmony");
    list.add("Modrix2468");
    list.add("IamSillhere");
    list.add("Dyronic");
    file.addDefault("Nickname.list", list);
    
    CityBuildCore.saveFile(file, FILE);
  }
  
  public static void updateNickSettingsInvFile() {
    File FILE = new File("plugins/CityBuild/Inventory/", "nicksettings.yml");
    FileConfiguration file = org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(FILE);
    
    file.addDefault("settings.addnickname", "Your new name is&8: &e%NAME%&7.");
    file.addDefault("settings.removenickname", "Your name has been removed.");
    
    file.addDefault("settings.normalstate", "&7Normal");
    file.addDefault("settings.premiumstate", "&6Premium");
    file.addDefault("settings.activated", "&aActivated");
    file.addDefault("settings.deactivated", "&cDeactivated");
    file.addDefault("settings.nick", "Your name is now&8: &c%NAME%");
    file.addDefault("settings.unnick", "Your Nickname has been removed.");
    file.addDefault("settings.waitfornick", "Please wait a moment, before you can use this again.");
    
    file.addDefault("inv.settings.name", "&8» &eNick Settings");
    file.addDefault("inv.settings.size", Integer.valueOf(27));
    file.addDefault("inv.settings.glasenabled", Boolean.valueOf(true));
    file.addDefault("inv.settings.animation", Boolean.valueOf(true));
    file.addDefault("inv.settings.glascolorPRIM", Integer.valueOf(0));
    file.addDefault("inv.settings.glascolorSEC", Integer.valueOf(7));
    
    List<String> lore = new java.util.ArrayList();
    lore.add("&8&m--------------------");
    lore.add("&7Choose whether you want to be");
    lore.add("&7nicked as a normal/premium player");
    lore.add("&7");
    lore.add("&8» %STATE%");
    CityBuildCore.saveItemInFile(file, "inv.items.premiumitem", 15, 266, 0, "&8● &6Name Type", lore, Boolean.valueOf(false));
    List<String> lore1 = new java.util.ArrayList();
    lore1.add("&8&m--------------------");
    lore1.add("&7Select, if you want to be nicked by joining.");
    lore1.add("&7");
    lore1.add("&8» %STATE%");
    CityBuildCore.saveItemInFile(file, "inv.items.autonickitem", 11, 421, 0, "&8● &6Autonicker", lore1, Boolean.valueOf(false));
    
    CityBuildCore.saveFile(file, FILE);
  }
}
