name: Villager-Shop
version: 1.0
main: de.undermain.shop.main.Main

commands:
   shop:
      description: shop
   coins:
      description: coins
   setspawn:
      description: setspawn
   spawn:
      description:
   creative:
      description:
   survival:
      description:
   heal:
      description:
   item:
      description:
   ontime:
      description:
   giveall:
      description:
   chatclear:
      description:
   setwarp:
      description:
   warp:
      description: