name: Ticket-System
version: 1.1
main: de.undermain.main.Main

commands: 
   setlogin:
      description:
   status:
      description: 
   check:
      description:
   deluser:
      description:
      

   